import Cloudy from "./pictures/Cloudy.png";
import LightRain from "./pictures/LightRain.png";
import Snow from "./pictures/Snow.png";
import Sunny from "./pictures/Sunny.png";
import Windy from "./pictures/Windy.png";
import moment from "moment";

export const countryList = [
  {
    countryName: "China",
    cityList: ["Beijing", "Shanghai"],
  },
  {
    countryName: "Japan",
    cityList: ["Tokyo", "Osaka"],
  },
];

export const timezone = [
  { country: "China", timezone: "Asia/Shanghai" },
  { country: "Japan", timezone: "Japan" },
];

export const todayData = [
  {
    cityName: "Beijing",
    todayWeather: [
      { img: Cloudy, time: "00:00", temperature: "22℃" },
      { img: Sunny, time: "01:00", temperature: "20℃" },
      { img: Sunny, time: "02:00", temperature: "25℃" },
      { img: LightRain, time: "03:00", temperature: "20℃" },
      { img: Cloudy, time: "04:00", temperature: "20℃" },
      { img: Cloudy, time: "05:00", temperature: "21℃" },
      { img: Snow, time: "06:00", temperature: "20℃" },
      { img: Cloudy, time: "07:00", temperature: "20℃" },
      { img: Sunny, time: "08:00", temperature: "20℃" },
      { img: Cloudy, time: "09:00", temperature: "21℃" },
      { img: Sunny, time: "10:00", temperature: "20℃" },
      { img: Cloudy, time: "11:00", temperature: "22℃" },
      { img: Snow, time: "12:00", temperature: "20℃" },
      { img: Cloudy, time: "13:00", temperature: "20℃" },
      { img: Cloudy, time: "14:00", temperature: "20℃" },
      { img: Windy, time: "15:00", temperature: "21℃" },
      { img: Cloudy, time: "16:00", temperature: "20℃" },
      { img: Sunny, time: "17:00", temperature: "20℃" },
      { img: Cloudy, time: "18:00", temperature: "23℃" },
      { img: Cloudy, time: "19:00", temperature: "20℃" },
      { img: Sunny, time: "20:00", temperature: "24℃" },
      { img: Sunny, time: "21:00", temperature: "20℃" },
      { img: Cloudy, time: "22:00", temperature: "20℃" },
      { img: Sunny, time: "23:00", temperature: "20℃" },
    ],
  },
  {
    cityName: "Shanghai",
    todayWeather: [
      { img: Cloudy, time: "00:00", temperature: "20℃" },
      { img: LightRain, time: "01:00", temperature: "20℃" },
      { img: Snow, time: "02:00", temperature: "21℃" },
      { img: LightRain, time: "03:00", temperature: "20℃" },
      { img: Cloudy, time: "04:00", temperature: "22℃" },
      { img: Cloudy, time: "05:00", temperature: "20℃" },
      { img: Snow, time: "06:00", temperature: "20℃" },
      { img: Cloudy, time: "07:00", temperature: "20℃" },
      { img: Sunny, time: "08:00", temperature: "23℃" },
      { img: Cloudy, time: "09:00", temperature: "20℃" },
      { img: LightRain, time: "10:00", temperature: "20℃" },
      { img: Cloudy, time: "11:00", temperature: "20℃" },
      { img: Snow, time: "12:00", temperature: "23℃" },
      { img: Cloudy, time: "13:00", temperature: "20℃" },
      { img: Cloudy, time: "14:00", temperature: "20℃" },
      { img: Windy, time: "15:00", temperature: "21℃" },
      { img: Cloudy, time: "16:00", temperature: "20℃" },
      { img: Cloudy, time: "17:00", temperature: "20℃" },
      { img: Cloudy, time: "18:00", temperature: "20℃" },
      { img: Cloudy, time: "19:00", temperature: "25℃" },
      { img: Cloudy, time: "20:00", temperature: "20℃" },
      { img: Sunny, time: "21:00", temperature: "20℃" },
      { img: Cloudy, time: "22:00", temperature: "24℃" },
      { img: Sunny, time: "23:00", temperature: "20℃" },
    ],
  },
  {
    cityName: "Tokyo",
    todayWeather: [
      { img: LightRain, time: "00:00", temperature: "20℃" },
      { img: LightRain, time: "01:00", temperature: "22℃" },
      { img: LightRain, time: "02:00", temperature: "20℃" },
      { img: LightRain, time: "03:00", temperature: "20℃" },
      { img: Cloudy, time: "04:00", temperature: "21℃" },
      { img: Cloudy, time: "05:00", temperature: "20℃" },
      { img: LightRain, time: "06:00", temperature: "20℃" },
      { img: LightRain, time: "07:00", temperature: "20℃" },
      { img: LightRain, time: "08:00", temperature: "20℃" },
      { img: Cloudy, time: "09:00", temperature: "21℃" },
      { img: LightRain, time: "10:00", temperature: "20℃" },
      { img: Cloudy, time: "11:00", temperature: "20℃" },
      { img: LightRain, time: "12:00", temperature: "20℃" },
      { img: Cloudy, time: "13:00", temperature: "20℃" },
      { img: Cloudy, time: "14:00", temperature: "21℃" },
      { img: Windy, time: "15:00", temperature: "20℃" },
      { img: Cloudy, time: "16:00", temperature: "20℃" },
      { img: Cloudy, time: "17:00", temperature: "21℃" },
      { img: Cloudy, time: "18:00", temperature: "20℃" },
      { img: Cloudy, time: "19:00", temperature: "20℃" },
      { img: Cloudy, time: "20:00", temperature: "21℃" },
      { img: Sunny, time: "21:00", temperature: "20℃" },
      { img: Cloudy, time: "22:00", temperature: "20℃" },
      { img: Sunny, time: "23:00", temperature: "21℃" },
    ],
  },
  {
    cityName: "Osaka",
    todayWeather: [
      { img: Cloudy, time: "00:00", temperature: "21℃" },
      { img: LightRain, time: "01:00", temperature: "20℃" },
      { img: Sunny, time: "02:00", temperature: "20℃" },
      { img: LightRain, time: "03:00", temperature: "20℃" },
      { img: Cloudy, time: "04:00", temperature: "21℃" },
      { img: Cloudy, time: "05:00", temperature: "20℃" },
      { img: Sunny, time: "06:00", temperature: "20℃" },
      { img: Cloudy, time: "07:00", temperature: "20℃" },
      { img: Sunny, time: "08:00", temperature: "20℃" },
      { img: Cloudy, time: "09:00", temperature: "21℃" },
      { img: LightRain, time: "10:00", temperature: "20℃" },
      { img: Cloudy, time: "11:00", temperature: "20℃" },
      { img: Sunny, time: "12:00", temperature: "20℃" },
      { img: Cloudy, time: "13:00", temperature: "20℃" },
      { img: Cloudy, time: "14:00", temperature: "20℃" },
      { img: Windy, time: "15:00", temperature: "21℃" },
      { img: Cloudy, time: "16:00", temperature: "20℃" },
      { img: Sunny, time: "17:00", temperature: "20℃" },
      { img: Cloudy, time: "18:00", temperature: "20℃" },
      { img: Sunny, time: "19:00", temperature: "20℃" },
      { img: Cloudy, time: "20:00", temperature: "21℃" },
      { img: Sunny, time: "21:00", temperature: "20℃" },
      { img: Cloudy, time: "22:00", temperature: "20℃" },
      { img: Sunny, time: "23:00", temperature: "21℃" },
    ],
  },
];

export const dateArray = [...Array(15).keys()].map((value) =>
  moment()
    .add(value + 1, "d")
    .format("MM/DD")
);

export const futureData = [
  {
    cityName: "Beijing",
    futureWeather: {
      high: [
        "20℃",
        "24℃",
        "18℃",
        "21℃",
        "21℃",
        "25℃",
        "23℃",
        "22℃",
        "25℃",
        "18℃",
        "20℃",
        "18℃",
        "23℃",
        "24℃",
        "25℃",
      ],
      low: [
        "18℃",
        "16℃",
        "15℃",
        "20℃",
        "15℃",
        "17℃",
        "19℃",
        "18℃",
        "21℃",
        "18℃",
        "19℃",
        "17℃",
        "19℃",
        "22℃",
        "16℃",
      ],
    },
  },
  {
    cityName: "Shanghai",
    futureWeather: {
      high: [
        "25℃",
        "20℃",
        "21℃",
        "20℃",
        "24℃",
        "24℃",
        "25℃",
        "21℃",
        "24℃",
        "25℃",
        "25℃",
        "21℃",
        "23℃",
        "25℃",
        "24℃",
      ],
      low: [
        "16℃",
        "17℃",
        "18℃",
        "16℃",
        "20℃",
        "17℃",
        "17℃",
        "17℃",
        "15℃",
        "20℃",
        "19℃",
        "20℃",
        "22℃",
        "22℃",
        "15℃",
      ],
    },
  },
  {
    cityName: "Tokyo",
    futureWeather: {
      high: [
        "17℃",
        "22℃",
        "23℃",
        "19℃",
        "22℃",
        "23℃",
        "21℃",
        "23℃",
        "25℃",
        "21℃",
        "19℃",
        "23℃",
        "24℃",
        "20℃",
        "17℃",
      ],
      low: [
        "15℃",
        "16℃",
        "19℃",
        "17℃",
        "20℃",
        "18℃",
        "17℃",
        "21℃",
        "20℃",
        "20℃",
        "16℃",
        "16℃",
        "16℃",
        "15℃",
        "15℃",
      ],
    },
  },
  {
    cityName: "Osaka",
    futureWeather: {
      high: [
        "20℃",
        "22℃",
        "25℃",
        "24℃",
        "25℃",
        "24℃",
        "21℃",
        "19℃",
        "21℃",
        "19℃",
        "18℃",
        "24℃",
        "24℃",
        "23℃",
        "22℃",
      ],
      low: [
        "17℃",
        "15℃",
        "25℃",
        "23℃",
        "18℃",
        "19℃",
        "18℃",
        "17℃",
        "15℃",
        "16℃",
        "17℃",
        "22℃",
        "20℃",
        "16℃",
        "19℃",
      ],
    },
  },
];
